### PR TITLE
Deployables create improve test coverage

### PR DESCRIPTION
**Pull request by hacxman**
some (2) of those fails though, I believe it is due to current implementation being incorrect
'fixes' #322

### CODE REVIEW

**Comment by n1zyy** [comment]
@hacxman - This looks like it needs to be rebased against master.

**Comment by hacxman** [comment]
rebased & fixed whitespace error

**Comment by martinpovolny** [comment]
@hacxman so to merge this we would probably like to fix the implementation in the same pull-request

or do you have different idea?

**Comment by martinpovolny** [comment]
nice tests, code finally fixed ;-)

ack and merging

**Pull request merged**
