### PR TITLE
BaseImages#show implementation

### PR DESCRIPTION
**Pull request by n1zyy**
This is a series of patches for the tim-stable branch that enables the image detail page.

### CODE REVIEW

**Comment by n1zyy** [comment]
A few things I'm aware of that are non-perfect:
1. The link to push ProviderImages looks properly-constructed, but that method doesn't presently work. I believe this needs separate attention, though.
2. The "View Image Template XML" link does not work. I put a FIXME where I link to it. I also believe that this needs separate fixing.
3. I get a couple warnings (see below) about duplicate constants at startup. However, I cannot find them used anywhere else. Might this be something odd going on with initializers?

```
/home/a/aeolus/conductor/src/app/decorators/models/tim/provider_image_decorator.rb:25: warning: already initialized constant STATUS_COMPLETE
/home/a/aeolus/conductor/src/app/decorators/models/tim/provider_image_decorator.rb:26: warning: already initialized constant STATUS_IMPORTED
```

**Comment by jprovaznik** [comment]
Hi Matt, I've added a few comments, but most of it are minor things. Only bigger thing which I'm missing is some way how to build newely create image ("rebuild" button), or was the plan to implement this in some oc upcoming patches?
Otherwise it looks good.

Btw, it seems this patchset breaks rspec tests.

**Comment by n1zyy** [comment]
It seems like something is wrong with my test setup. I see that there are failures on Travis, though; I'll investigate.

I somehow overlooked the Rebuild feature. D'oh! I'll implement that, fix up what you mention, and figure out what's wrong with tests, then re-send. Thanks for the review!

**Comment by n1zyy** [comment]
Updated and resent: https://github.com/aeolusproject/conductor/pull/256

**Pull request closed without merging**
