### PR TITLE
costs for conductor

### LINKED ISSUE #192: Cost-based provider selection
UI for adding costs
UI for managing selection algorithm 
actual algorithm

### PR DESCRIPTION
**Pull request by martinpovolny**
implements:
- assign cost to backend hardware profiles
- calculate costs for instances, deployments etc
- simple cost-bases provider selection strategy

closes #192

### CODE REVIEW

**Comment by jprovaznik** [comment]
If I set a cost value (no matter what billing model is selected), then final cost on hardware profile show page is always cost*2.

**Comment by jprovaznik** [comment]
doesn't have to be part of this patch, but we will need to give users more info what range of cost values is expected - now I was wondering why I'm getting maximum penalty for two different costs (both in range 1-10), after checking the code it seems that expected range is 0.01-0.9

**Comment by martinpovolny** [comment]
there is a constant in the code, that is meant to handle this -- if you set it to a higher value, you move the expected price range

there's a note that this might become a config option for the strategy if needed

so if there's a need (the prices actually would be needed way out of the expected range) I can turn that constant into a config option with minimal effort

**Comment by jprovaznik** [comment]
re: cost values range - we discussed this over irc and agreed that information about what is reasonable cost value range should be displayed when editting costs. This will be fixed in some way in seprate patch.

**Pull request merged**
