### PR TITLE
Converge-ui fonts symlink fix

### PR DESCRIPTION
**Pull request by jtomasek**
Latest converge-ui returns back to original fonts folder structure. So the converge-ui
fonts are now symlinked in public/fonts/converge-ui. If we have custom fonts in
Conductor, we should put them into public/fonts dir.

### CODE REVIEW

**Comment by ifarkas** [comment]
The rpm building throws the following error: 
app/stylesheets/layout.scss (Line 4: File to import not found or unreadable: converge-ui/composites/content_elements.

Not sure if it's related but it seems that the converge-ui update is causing the failure.

**Comment by jeckersb** [comment]
This builds ok for me, but I'm worried that it's going to break because the fonts end up being nested a directory deeper than they were before.

Before:

/usr/share/aeolus-conductor/public/fonts/LiberationSans-Bold-webfont.eot -> ../../vendor/converge-ui/fonts/LiberationSans-Bold-webfont.eot

After, only the directory is linked:

/usr/share/aeolus-conductor/public/fonts/converge-ui -> ../../vendor/converge-ui/fonts

Which means the above font is now canonically at /usr/share/aeolus-conductor/public/fonts/converge-ui/LiberationSans-Bold-webfont.eot (note the new addition of /converge-ui/ in the path)

**Comment by jtomasek** [comment]
Note (regarding IRC discussion): It will not break because the links in converge-ui changed, so the symlink this patch introduces is actually making the fonts work with the new converge-ui

**Comment by ifarkas** [comment]
I needed to build and install the converge-ui rpm from source and it solved the issue.
ACK

**Pull request merged**
