### PR TITLE
Issue 171 - Instances api - list, show, entrypoint

### PR DESCRIPTION
**Pull request by rwsu**
A few issues to be addressed in a future patch:
1. Assembly xml is shown as quoted.
2. Image uuids should be replaced with references to actual resources.

### CODE REVIEW

**Comment by hacxman** [comment]
Hi, some of the lines are too long, please break it down so that we could see it without wrapping.
In view it's sufficient to keep the indentation level.

Also it might be worth to split _it_ in spec so that each _should_ is in it's own _it_. It's not a blocker though.

Other than that it looks OK to me, so conditional ACK.
Have a nice day.

**Comment by hacxman** [comment]
Well, unfortunately I found out that it's not worth to split _it_ into a lot of new _it_s because of speed.
When I split _it_s when testing XML content, the spec took 3.5 times longer :(

**Comment by rwsu** [comment]
This patch needs to be revised to show the entire resource representation in top level collections. I am planning to submit another pull for the next milestone.

**Comment by rwsu** [comment]
Closing. Replaced by pull #273.

**Pull request closed without merging**
