### PR TITLE
First patchset for conversion to gettext

### PR DESCRIPTION
**Pull request by jzigmund**
This is the 1st part for converting to using gettext as a default i18n approach. It contains: fixation of codes and eng. dictionary before conversion, setting up the configuration for using gettext_i18n_rails and conversion of simple t-keys in source code.

### CODE REVIEW

**Comment by jzigmund** [comment]
I need to fixed the tests.

The build was broken.
Repository  aeolusproject/conductor
Build #378  http://travis-ci.org/aeolusproject/conductor/builds/3019409
Changeset   https://github.com/aeolusproject/conductor/pull/163

**Comment by jzigmund** [comment]
Updated by additional patches - t-keys with variables
Number of remaining t-keys = 64 (mostly t-keys with interpolation or containing pluralization)

**Comment by martinpovolny** [comment]
please check the copyright headers; e.g.: conductor / src / locale / app.pot

**Comment by jzigmund** [comment]
Finally all issues are fixed, it's ready to review.

Next:
I'll update i18n wiki page:
https://redmine.aeolusproject.org/redmine/projects/aeolus/wiki/Internationalization

**Comment by jzigmund** [comment]
After my longer PTO, I have rebased the whole patchset against master.

**Comment by jprovaznik** [comment]
Hi Jozef and anyone who will review this patch, please hold on with merging this patch until the Tim integration patch is pushed.

**Comment by jzigmund** [comment]
Ok I'll bear in my mind.

**Comment by jzigmund** [comment]
Rebased after TIM integrarion patchset ... please review it

**Comment by martinpovolny** [comment]
the case at deployables_controller.rb 'show' would look much better if it was a hash lookup and the hash was defined outside the method

too much pasta in the 'show ' method already

**Comment by martinpovolny** [comment]
aaaaand, why do we use "" and not ''? 

in such a number it already must make a difference and I also remember some memory problem in DC related to the usage in ""

**Comment by jzigmund** [comment]
Hi, this patchset is invalid so I've closed this pull request.

Recent 1st patchset located on https://github.com/aeolusproject/conductor/issues/397

**Pull request closed without merging**
