### PR TITLE
List all provider's hardware profiles

### PR DESCRIPTION
**Pull request by jzigmund**
Added tab 'Hardware Profiles' to provider's details. User is now abled
to see all hardware profiles of defined provider.

https://github.com/aeolusproject/conductor/issues/319

### CODE REVIEW

**Comment by jzigmund** [comment]
For me all tests are green, however Travis result is different (check log for rspec on 1.9.3). Is it possible to rerun the tests without updating pull request?

**Comment by jcoufal** [comment]
Try to close and open the issue.

**Comment by jcoufal** [comment]
From the UI point of view (visual and functional) looks OK. Need some code check from somebody else.

#### Tests
- **spec has 1 failure:**
  - spec ./spec/services/data_service_active_record_spec.rb:21 # DataServiceActiveRecord should calculate the total instance quota usage for a provider with a number of cloud accounts
- cucumber passed.

**Comment by jzigmund** [comment]
close/reopen helped .. all tests green, let's review it!

**Comment by jprovaznik** [comment]
works fine, looks good, merging

**Pull request merged**
