### PR TITLE
add missing key to provider_accounts_realms table

### PR DESCRIPTION
**Pull request by martinpovolny**

### CODE REVIEW

**Comment by jprovaznik** [comment]
ACK

**Comment by rwsu** [comment]
The provider_accounts_realms table was renamed to provider_accounts_provider_realms. This migration will need to be adjusted to use the new name.

The build broke after this was merged. It is interesting that this pull request didn't trigger a travis build, I wonder if there was some infrastructure issue.

**Comment by martinpovolny** [comment]
Could be the renaming was committed after the pull request was created and travis did not retest yet?

**Comment by martinpovolny** [comment]
fixed here:

https://github.com/aeolusproject/conductor/pull/128

tests pass, travis looks happy

**Pull request merged**
