### PR TITLE
fix issue #149 - label in pool_families/new form 

### PR DESCRIPTION
**Pull request by martinpovolny**
fix issue #149 - label in pool_families/new form

### CODE REVIEW

**Comment by humaton** [comment]
ack.

**Comment by jtomasek** [comment]
NACK, the label in the form is label for actual activerecord model attribute. So all you have to do to get proper label is to fix the translation in config/locales/activerecord/en.yml (line 223)

**Comment by humaton** [comment]
Ahh my fault I wasn't myself today morning. How do I revert a merge here?

**Comment by jtomasek** [comment]
I am not sure about github feature, but either create git revert patch or better solution I think is just to create patch that fixes this one and introduces the correct change... I can do that, if you want.

**Comment by humaton** [comment]
That will be awesome, thanks.

**Comment by jtomasek** [comment]
fix: https://github.com/aeolusproject/conductor/pull/154

**Pull request merged**
